Backport top level configure.ac from 2.99 r21251, removing unneeded support for Lua, bzrobots, Freetype, and FTGL. Use 3rd party software that is in src/other instead of what is directly under the src directory. Improve some whitespace.
git-svn-id: https://svn.code.sf.net/p/bzflag/code/trunk/bzflag@21696 08b3d480-bf2c-0410-a26f-811ee3361c24

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -48,6 +48,8 @@ EXTRA_DIST = \
 	README.WINDOWS \
 	README.XMINGW
 
+DISTCLEANFILES = config.cache.*
+
 MAINTAINERCLEANFILES = \
 	aclocal.m4 \
 	configure \
@@ -78,3 +80,20 @@ debian-release: debian/changelog dist
 	cp debian/changelog $(distdir)/debian/
 	(cd $(distdir) && debian/buildsnap release)
 
+# make sure all files are in the repository are also in the dist.
+# make sure files that should not be in the distribution in fact are
+# not included.
+dist-hook:
+	files="`find . -name entries -exec grep 'name=' {} /dev/null \; | sed 's/:[[:space:]]*name=\"\(.*\)\"/\1/g' | sed 's/\/\.svn\/entries/\//g' | grep -v 'bzflag-' | grep -v '\/$$'`" ; \
+	missing=0 ; \
+	for file in $$files ; do \
+		if test ! -e $(distdir)/$$file ; then \
+			missing=1 ; \
+			echo "MISSING FROM DIST: $$file" ; \
+		fi ; \
+	done ; \
+	if test "x$$missing" = "x1" ; then \
+		exit 1 ; \
+	fi
+	find $(distdir) -type f \( -name Makefile -o -name config.log -o -name config.status \) -exec rm -f {} \;
+	find $(distdir) -type d \( -name .deps -o -name .svn -o -name autom4te.cache \) -prune -exec rm -rf {} \;
